### ISSUE TITLE
Any way to add extractor-args to download command

### ISSUE THREAD

**Issue by cwl-uml** [nonoo/yt-dlp-telegram-bot#2]
Hi,

Is there any way to add command arguments `extractor-args` when passing to yt-dlp download process?

Or is it possible to let user pass extra command arguments when executing the bot?

Thanks for the bot!

**Comment by nonoo** [comment]
Currently there's no way to pass extractor args to yt-dlp, as the used yt-dlp lib (goutubedl) does not support passing that to yt-dlp.
