### ISSUE TITLE
Pls Make A Dedicated Tutorial Video

### ISSUE THREAD

**Issue by Abel360w** [nonoo/yt-dlp-telegram-bot#3]
### Hello i am abel i am trying to make a telegram on replit but i cannot. because i dont have enough information to run your code so pls make a tutorial video on how to run this code on Replit .Pls Its A Request 😥

- **And This Is  My Bot [FetchRobot](https://t.me/FetchRobot) Currently Its in a Develpoment Stage It can go ON OR OFF AT ANYTIME But I need your bot Code So that I am Able to Upload files larger than 50mb through telegram .So Kindly Pls Make A Tutorial ****** 

- [ Respectfully Abel]

**Comment by nonoo** [comment]
You can find the installation/usage instructions in the `README.md` file.

**Comment by Abel360w** [comment]
Bro I am Not A Programmer Can You Pls Atleast Tell Me The Steps To How Install And Make It work on Replit Pls Its A Humble Request 

> Respectfully Abel
