### ISSUE TITLE
How to use cookies?

### ISSUE THREAD

**Issue by MaxBu** [nonoo/yt-dlp-telegram-bot#7]
Hello. I was add YTDLP_COOKIES=cookies.txt in config.inc.sh and put text file on server but I see bot don't use parameter --cookies. I don't use docker. Is there a way to use cookies?

**Comment by MaxBu** [comment]
I need to rebuild my binary file after making new env var?

**Comment by nonoo** [comment]
You don't need to rebuild it. Environment variables can be passed to the
already built binary.

**Comment by MaxBu** [comment]
I see yt-dlp from bot don't use "--cookies" is this normal? I was try to use my cookies.txt file for yt-dlp manually and there is no problem with download. How to activate "--cookies" in bot?
![image](https://github.com/nonoo/yt-dlp-telegram-bot/assets/10898637/01946c83-4067-4fa7-8217-d6bbcb77e5e2)

**Comment by nonoo** [comment]
Set the cookie data in the YTDLP_COOKIES environment variable before starting the bot.

**Comment by MaxBu** [comment]
It's already there. This is part of "sudo env" command.
![sudo_env](https://github.com/nonoo/yt-dlp-telegram-bot/assets/10898637/bba671e6-caaa-4aca-8c9e-6238d515a65f)

**Comment by MaxBu** [comment]
Oh sorry, I found my trouble. It was not valid cookie text. Thanks for helping!

**Comment by MaxBu** [comment]
found strange behavior:
1. Created the YTDLP_COOKIES environment variable (netscape format of cookies)
2. Launched the bot via run.sh
3. Checked the created file in the /tmp/ytdlp-cookies.txt. The value as in the environment variable YTDLP_COOKIES
4. But the bot itself does not use cookies
If I try to use "ytdlp --cookies /tmb/ytdlp-cookies.txt" from command line manually everything is ok and content was downloaded
