### ISSUE TITLE
found strange behavior with cookies:

### ISSUE THREAD

**Issue by MaxBu** [nonoo/yt-dlp-telegram-bot#8]
found strange behavior:
1. Created the YTDLP_COOKIES environment variable (netscape format of cookies)
2. Launched the bot via run.sh
3. Checked the created file in the /tmp/ytdlp-cookies.txt. The value as in the environment variable YTDLP_COOKIES
4. But the bot itself does not use cookies
If I try to use "ytdlp --cookies /tmb/ytdlp-cookies.txt" from command line manually everything is ok and content was downloaded

PS. binary file was build on another machine

_Originally posted by @MaxBu in https://github.com/nonoo/yt-dlp-telegram-bot/issues/7#issuecomment-1855663143_

**Comment by MaxBu** [comment]
perhaps this is due to the characters `\` and `"` in environment file

**Comment by nonoo** [comment]
This is not a yt-dlp-telegram-bot issue. Please make sure the cookie data follows the Netscape cookie data format and it does not have any special characters.

**Comment by MaxBu** [comment]
> This is not a yt-dlp-telegram-bot issue. Please make sure the cookie data follows the Netscape cookie data format and it does not have any special characters.

How is this possible, when I run "./run.sh" in the yt-dlp-telegram-bot folder, the program creates a file "/tmp/ytdlp-cookies.txt" with the value from the YTDLP_COOKIES environment variable. And this value is valid for yt-dlp. If I use --cookies, I can download a video from a website that requires login. But if I send the URL to the bot, I get an authorization error (the website doesn't see cookies).
